version: '3'
services:
  postgres:
    container_name: postgres
    image: arminc/clair-db:latest
    networks:
      - clair_net
  clair:
    container_name: clair
    image: arminc/clair-local-scan:latest
    networks:
      - clair_net
    depends_on:
      - postgres
  clair-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    image: clair-scanner:latest
    networks:
      - clair_net
    volumes:
      -  "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/scan"

networks:
  clair_net:
