version: '3'
services:
  postgres:
    image: arminc/clair-db:latest
  clair:
    image: arminc/clair-local-scan:latest
    depends_on:
      - postgres
  clair-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    image: clair-scanner:latest
    volumes:
      -  "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/scan"
